[project]
name = "ibis-django"
version = "1.0.0dev"
dependencies = [
    "django~=5.2.9",
    "django-environ",
    "isbnlib",
    "nameparser",
    "psycopg2",
    "requests",
    "titlecase",
    "urlobject",
    "waitress",
    "whitenoise",
]

[project.scripts]
ibis = "ibis.server:run"
